#* Project metadata
[project]
name = "TransMelo"
version = "0.1.0"
description = "A way to optimize TransMilenio's routes"
authors = [
    { name = "Santiago Rocha Pachón", email = "srochap@unal.edu.co" },
    { name = "Daniel Santiago Melo Carrillo", email = "dmeloca@unal.edu.co" },
    { name = "Jesús Esteban Pérez Rodríguez", email = "jeperezro@unal.edu.co" },
    { name = "Juan Guillermo ", email = "" }    
]
license = "MIT"
readme = "README.md"

#* Python version requirement
[requires]
python_version = ">=3.6"

#* Dependencies
[dependencies]
cython = ">=3.0.12"
requests = ">=2.25.1"
numpy = ">=1.19.5"
pandas = ">=1.2.1"
setuptools = ">=75.8.0"