#* Project metadata
[project]
name = "TransMelo"
version = "0.1.0"
description = "A way to optimize TransMilenio's routes"
authors = ["Santiago Rocha Pachon <srochap@unal.edu.co>"]
license = "MIT"
readme = "README.md"

#* Python version requirement
[requires]
python_version = ">=3.6"

#* Dependencies
[dependencies]
cython = ">=3.0.12"
requests = ">=2.25.1"
numpy = ">=1.19.5"
pandas = ">=1.2.1"
setuptools = ">=75.8.0"